### ISSUE TITLE
pip install does not include jinja2

### ISSUE THREAD

**Issue by lundybernard** [notsag/yaml-resume#34]
**jinja2 is not installed**
Traceback (most recent call last):
  File "resume/bin/yaml-resume", line 5, in <module>
    from yaml_resume.cli import cli
  File "resume/lib/python3.10/site-packages/yaml_resume/cli.py", line 4, in <module>
    from jinja2 import Environment, PackageLoader
ModuleNotFoundError: No module named 'jinja2'

**To Reproduce**
1. `pip install yaml-resume`
2. `yaml-resume init FILENAME resume.yaml`

**Expected behavior**
The CLA should run without an exception

**Desktop (please complete the following information):**
 - OS: Unbuntu
 - Version: 20.04
 - Python Version: 3.10.0

**Comment by rojinmroy** [comment]
That might be because jinja2 and weasyprint were added as requirements after the PYPI release. Might need to manually install them to get it working until another release.
